<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payment_transactions', function (Blueprint $table) {
            $table->id();

            $table->foreignId('order_id')
                ->constrained()
                ->cascadeOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Payment Provider
            |--------------------------------------------------------------------------
            */

            $table->string('provider', 50);

            /*
            |--------------------------------------------------------------------------
            | Merchant Transaction Reference
            |--------------------------------------------------------------------------
            |
            | This is generated by our application and sent to the gateway.
            |
            */

            $table->string('transaction_reference', 100)
                ->unique();

            /*
            |--------------------------------------------------------------------------
            | Gateway Transaction Reference
            |--------------------------------------------------------------------------
            |
            | The payment provider may return its own transaction/reference ID.
            |
            */

            $table->string('gateway_transaction_id', 150)
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Amount
            |--------------------------------------------------------------------------
            */

            $table->decimal('amount', 12, 2);

            $table->string('currency', 3)
                ->default('PKR');

            /*
            |--------------------------------------------------------------------------
            | Transaction Status
            |--------------------------------------------------------------------------
            */

            $table->string('status', 30)
                ->default('pending');

            /*
            |--------------------------------------------------------------------------
            | Gateway Response
            |--------------------------------------------------------------------------
            |
            | Useful for debugging/auditing.
            |
            */

            $table->string('response_code', 100)
                ->nullable();

            $table->text('response_message')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Gateway Payloads
            |--------------------------------------------------------------------------
            |
            | Store gateway request/response data when appropriate.
            |
            | Never store sensitive credentials, passwords, card CVV,
            | PINs, or other secrets.
            |
            */

            $table->json('request_payload')
                ->nullable();

            $table->json('response_payload')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Payment Timestamps
            |--------------------------------------------------------------------------
            */

            $table->timestamp('initiated_at')
                ->nullable();

            $table->timestamp('paid_at')
                ->nullable();

            $table->timestamp('failed_at')
                ->nullable();

            $table->timestamps();

            /*
            |--------------------------------------------------------------------------
            | Indexes
            |--------------------------------------------------------------------------
            */

            $table->index([
                'order_id',
                'provider',
            ]);

            $table->index('status');

            $table->index('gateway_transaction_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payment_transactions');
    }
};
